java 21 no longer supports building java 7 code
The error we get is:

Error:  COMPILATION ERROR :
Error:  Source option 7 is no longer supported. Use 8 or later.
Error:  Target option 7 is no longer supported. Use 8 or later.

Fixing the build now to build for java 8, but we have to verify
if we can support java 7 at all anymore.

Related (#15)